#services:
#  redis:
#    container_name: redis-container
#    image: redis
#    ports:
#      - "6379:6379"
#
#  goodsapp:
#    image: heechannoh/goods-project-image:latest  # Docker Hub에 올린 애플리케이션 이미지
#    container_name: GoodsApp
#    depends_on:
#      - redis
#      - es
#    ports:
#      - "8080:8080"
#    restart: always